### ISSUE TITLE
The bitbucket icon (svg) is not working

### ISSUE THREAD

**Issue by joeplaa** [walkxcode/dashboard-icons#600] opened 2024-02-07 09:16 UTC
Hi,

The Atlassian Bitbucket icon ([https://github.com/walkxcode/dashboard-icons/blob/main/svg/atlassian-bitbucket.svg](https://github.com/walkxcode/dashboard-icons/blob/main/svg/atlassian-bitbucket.svg)) is not loading / available on the CDN: `This XML file does not appear to have any style information associated with it. The document tree is shown below.`.

Other Atlassian icons like Confluence, Jira and Trello work fine.

- Bitbucket: [https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/svg/atlassian-bitbucket.svg](https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/svg/atlassian-bitbucket.svg)
- Confluence: [https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/atlassian-confluence.png](https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/atlassian-confluence.png)
- Jira: [https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/svg/jira.svg](https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/svg/jira.svg)
- Trello: [https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/svg/atlassian-trello.svg](https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/svg/atlassian-trello.svg)

**Comment by walkxcode** [comment] 2024-03-21 00:54
Hi, I am unable to reproduce. Are you still facing this issue?

**Comment by joeplaa** [comment] 2024-03-21 09:30
Yes. For example, loading the Jira icon on the right works, the Bitbucket item on the left results in an error.
![bitbucket-jira](https://github.com/walkxcode/dashboard-icons/assets/58688994/799e0ff5-479d-408a-bf78-dc283fac5715)

**Comment by walkxcode** [comment] 2024-03-21 21:54
Hi, could you check if it is fixed now?

**Comment by joeplaa** [comment] 2024-03-22 07:29
Not yet. CDN caching issue?

**Comment by walkxcode** [comment] 2024-03-22 14:53
Should work now!

**Comment by joeplaa** [comment] 2024-03-22 16:36
Yes, thanks!

**Closed** 2024-04-02 21:39 UTC
