### ISSUE TITLE
Net Alert X

### ISSUE THREAD

**Issue by stanthewizzard** [walkxcode/dashboard-icons#670] opened 2024-04-23 08:37 UTC
### Contribution Guidelines

- [X] I have read and agree to the [Contribution Guidelines](https://github.com/walkxcode/dashboard-icons/blob/main/CONTRIBUTING.md)

### Icon Name

Net Alert X

**Comment by stanthewizzard** [comment] 2024-04-23 08:37
https://github.com/jokob-sk/NetAlertX

**Comment by walkxcode** [comment] 2024-06-01 17:59
Duplicate of https://github.com/walkxcode/dashboard-icons/issues/667

**Closed by walkxcode** 2024-06-01 17:59 UTC
