### ISSUE TITLE
⚡ — *put a quick title describing your issue here*

### ISSUE THREAD

**Issue by firu82** [walkxcode/dashboard-icons#296] opened 2023-03-02 09:59 UTC
### Type

Icon request

### Info

icon request for mkvtoolnix , asustor and slskd

**Comment by walkxcode** [comment] 2023-03-07 23:45
All issues are temporarily on hold. Please refer to #316 for more info.

**Comment by walkxcode** [comment] 2023-04-14 10:09
Duplicate of #298

**Closed by walkxcode** 2023-04-14 10:09 UTC
Labels: ⚡️ Requests & Suggestions
